todo/urls.py
from django.urls import path

from . import views
app_name = 'todo' 

urlpatterns = [
    path('', views.home, name='home'),

    path('<int:todo_id>/todo_delete', views.todo_delete, name='todo_delete'),

    path('<int:todo_id>/todo_update', views.todo_update, name='todo_update'),
    
    path('todo_create/', views.todo_create, name='todo_create'),
    path('<int:todo_id>/todo_edit/', views.todo_edit, name = 'todo_edit'),
    path('<int:todo_id>/todo_edit_save/', views.todo_edit_save, name='todo_edit_save')
]

todo_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('todo.urls')),
    path('admin/', admin.site.urls),
]

todo/models.py
from django.db import models

# Create your models here.

class all_todo(models.Model) :
    title = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_completed = models.BooleanField(default=False)
    

todo/views.py
from django.shortcuts import render, redirect

from django.http import HttpResponse

from .models import all_todo

# Create your views here.

def home(request) :
    todos = all_todo.objects.order_by('-created_at')
  
    data = {'data': todos}
    return render(request, 'home.html', context= data)

def todo_create(request):
    
    title = request.POST['todo-title']
    all_todo.objects.create(title= title)
    return redirect('todo:home')
  
def todo_delete(request, todo_id):
    
    dl = all_todo.objects.get(id = todo_id)
    dl.delete()

    return redirect('todo:home')

def todo_update(request, todo_id):
    
    todo_obj = all_todo.objects.get(id = todo_id)
    if todo_obj.is_completed == False:
        todo_obj.is_completed = True
    else :
        todo_obj.is_completed = False
    
    todo_obj.save()
    
    return redirect('todo:home')

def todo_edit(request, todo_id):
    todo = all_todo.objects.get(id= todo_id)
    print(todo.title)
    data = {
        "title":todo.title,
        "todo_id":todo_id
            }
    return render(request, 'edit.html', context=data)

def todo_edit_save(request, todo_id) :
    todo = all_todo.objects.get(id=todo_id)
    todo.title = request.POST['todo-title']
    todo.save()
    return redirect('todo:home')

todo/templates/add.html
<form method ="post" action="{% url 'todo:create' %}">
    {% csrf_token %}

    <div class="mb-3 mt-3">
        <input
            type="text"
            class="form-control"
            name="todo-title"
            id=""
            aria-describedby="helpId"
            placeholder="Write your todo"
        />
      
    </div>
    <div class="text-center mb-3" >
        <button type="submit" class="btn btn-primary">
            Save
        </button>
    </div>
</form>

todo/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <title>Django Todo</title>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />

        <!-- Bootstrap CSS v5.2.1 -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous"
        />
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

        <link rel="stylesheet" href="{% static 'style.css' %}">
    
    </head>

    <body>
        <div class="container-sm !justify !spacing offset-md-3 col-md-6 offset-lg-3 col-lg-5">
            <h1 class="text-center mt-3"> Django Todo</h1>
        

            
        {% block content%}
        {% endblock %}
        </div>

        <!-- Bootstrap JavaScript Libraries -->
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"
        ></script>

        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
            integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

todo/templates/create.html
<form method ="post" action="{% url 'todo:todo_create' %}">
    {% csrf_token %}

    <div class="mb-3 mt-3">
        <input
            type="text"
            class="form-control"
            name="todo-title"
            id=""
            value=""
            aria-describedby="helpId"
            placeholder="Write your todo"
        />
      
    </div>
    <div class="text-center mb-3" >
        <button type="submit" class="btn btn-primary">
            Add Todo
        </button>
    </div>
</form>

todo/templates/edit.html
{% extends 'base.html' %}

{% block content %}
<form method ="post" action="{% url 'todo:todo_edit_save' todo_id %}">
    {% csrf_token %}

    <div class="mb-3 mt-3">
        <input
            type="text"
            class="form-control"
            name="todo-title"
            id=""
            value="{{title}}"
            aria-describedby="helpId"
            placeholder="Write your todo"
        />
      
    </div>
    <div class="text-center mb-3" >
        <button type="submit" class="btn btn-primary">
            Save Changes
        </button>
    </div>
</form>
{% endblock %}

todo/templates/home.html
{% extends 'base.html' %}
{% block content %}
        {% include "create.html" %}
        {% include "list.html" %}
{% endblock %}

todo/templates/list.html
<div class="">
    
    <ul class="list-group">
        {% for todo in data %}
    
            <li class="list-group-item text-white {% if todo.is_completed == 1 %} bg-dark
            {% else %} bg-secondary
            {% endif %}            
            ">
                <div class="d-inline-flex justify-content-between col-12 {% if todo.is_completed == 1 %} cus-line-through {% endif %}">
                    <div>

                    <!-- UPDATE BUTTON -->
                    
                    {% if todo.is_completed == 0 %}
                    <a href="{% url 'todo:todo_update' todo.id %}" class=" cus-link">
                        <i class="fa-regular fa-square"></i>
                    </a>
                    {% else %}
                    <a href="{% url 'todo:todo_update' todo.id %}" class="cus-link">
                        <i class="fas fa-check-square"></i> 
    
                    </a>
                    {% endif %}    
                
                    <!-- TODO TITLE -->

                    {{ todo.title }}

                    </div>
                    <div class="d-flex justify-content-between col-1">
                        
                        <!-- EDIT BUTTON -->
                        
                        <div class="d-inline">
                            <a href="{% url 'todo:todo_edit' todo.id %}">
                                <p class="fas fa-edit text-white"></p>
                            </a>
                        </div>
                        
                        <!-- DELETE BUTTON -->

                        <div class="d-inline">
                            <a href="{% url 'todo:todo_delete' todo.id %}" class = "">
                                <p class="fa-solid fa-trash  text-danger"></p>
                            </a>
                        </div>
    
                    </div>

                </div>
            </li>
            
        {% endfor %}
    </ul>
</div>